name: workflow-test

on:
#   push:
#     branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  full_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: guyarb/deny-not-updated-branch@v1.0.0
